### ISSUE TITLE
pquota -  limit on number of files exceeded

### ISSUE THREAD

**Issue by bedroge** [rug-cit-hpc/cluster-utilities#6]
I got the following error:

`[p251204@peregrine ~]$ pgquota 
Quotas for user p251204
Traceback (most recent call last):
  File "/usr/bin/pgquota", line 238, in <module>
    main()
  File "/usr/bin/pgquota", line 208, in main
    quota = Quota(g,d,args.d)
  File "/usr/bin/pgquota", line 95, in __init__
    self.fusage = int(self.ref[5])
ValueError: invalid literal for int() with base 10: '215183*'`

Apparently, the number of files is not being parsed correctly when the limit is exceeded (an asterisk is concatenated to the value):

`$ lfs quota -hg p251204 /home
Disk quotas for grp p251204 (gid 10251204):
     Filesystem    used   quota   limit   grace   files   quota   limit   grace
          /home  28.21G     30G     33G       -  215162* 204800  225280 6d23h36m52s
`

**Comment by klemenvon** [comment]
Made a fix for this and tested that it works. I'd suggest waiting before updating the rpm version till I get the OOD output sorted as well.

**Comment by bedroge** [comment]
Tested it, created a new RPM, and installed the new version on all nodes.
